apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx-week18
  name: deployport-service
spec:
  ports:
  - port: 8083
    protocol: TCP
    targetPort: 8083
  selector:
    app: nginx-week18
  type: NodePort
status:
  loadBalancer: {}
