kind: ConfigMap
apiVersion: v1
metadata:
  name: html-configmap
data:
  index.html: |
    <html>
       <body style="background-color:lightgreen;">
       <h1 style="font-family:arial">Welcome to GreenTeam's Pod</h1>
       </br>
       <h1 style="font-family:verdana;">
       <p>Hi there, This page is housed on a pod running Nginx!</p>
       </h1>
       </body>
    </html>
