apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-week18
  name: loadbalance-service
spec:
  ports:
  - port: 8765
    protocol: TCP
    targetPort: 9376
  selector:
    app: nginx-week18
  type: LoadBalancer
status:
  loadBalancer: {}
