apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-Test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-Test
  template:
    metadata:
      labels:
        app: myapp-Test
    spec:      
      containers:
      - name: nginx
        image: nginx:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8083
