apiVersion: v1
kind: Service
metadata:
  name: joseph-wk17-service
  labels:
    app: nginx
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: joseph-wk17-deploy
  labels:
    app: nginx
spec:
  replicas: 2    # creates this many replicas
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: joseph-week17