apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-test
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: myapp-test
  template:
    metadata:
      labels:
        app: myapp-test
    spec:
      containers:
        - name: nginx-webserver
          image: nginx
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
        - name: debian-test
          image: debian
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
      restartPolicy: Always
