apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-test
  template:
    metadata:
      labels:
        app: myapp-test
    spec:
      containers:
        - name: nginx-webserver
          image: nginx
          imagePullPolicy: Always
          resources:
            limits:
              memory: 128Mi
              cpu: 500m
          ports:
            - containerPort: 8081
        - name: debian-test
          image: debian
          imagePullPolicy: Always
          resources:
            limits:
              memory: 128Mi
              cpu: 500m
          ports:
            - containerPort: 8082
          command: ["/bin/sh"]
          args: ["-c", "while true; do echo hello; sleep 10;done"]
      restartPolicy: Always
